export default (req, res) => {
  res.status(200).json({
    code: 0,
    data: [
      {
        id: 1,
        pid: 0,
        title: "应用",
        sort: 1,
        display: 1,
        level: 0,
        child: [
          {
            id: 130,
            pid: 1,
            title: "无线通信",
            sort: 1,
            display: 1,
            level: 1,
            child: [
              {
                id: 138,
                pid: 130,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 139,
                pid: 130,
                title: "蜂窝标准测试",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 140,
                pid: 130,
                title: "无线连接测试",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 141,
                pid: 130,
                title: "物联网（IoT）测试",
                sort: 4,
                display: 1,
                level: 2,
              },
              {
                id: 142,
                pid: 130,
                title: "移动网络基础设施测试",
                sort: 5,
                display: 1,
                level: 2,
              },
              {
                id: 143,
                pid: 130,
                title: "移动网络测试",
                sort: 6,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 131,
            pid: 1,
            title: "移动网络",
            sort: 2,
            display: 1,
            level: 1,
            child: [
              {
                id: 144,
                pid: 131,
                title: "概述 ",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 145,
                pid: 131,
                title: "网络规划",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 146,
                pid: 131,
                title: "网络部署及优化",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 147,
                pid: 131,
                title: "故障排除",
                sort: 4,
                display: 1,
                level: 2,
              },
              {
                id: 148,
                pid: 131,
                title: "干扰排查",
                sort: 5,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 132,
            pid: 1,
            title: "频谱监测",
            sort: 3,
            display: 1,
            level: 1,
            child: [
              {
                id: 149,
                pid: 132,
                title: "概述 ",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 150,
                pid: 132,
                title: "无线电监测",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 151,
                pid: 132,
                title: "无线电测向",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 152,
                pid: 132,
                title: "频谱评估",
                sort: 4,
                display: 1,
                level: 2,
              },
              {
                id: 153,
                pid: 132,
                title: "台站核查",
                sort: 5,
                display: 1,
                level: 2,
              },
              {
                id: 154,
                pid: 132,
                title: "重大活动保障",
                sort: 6,
                display: 1,
                level: 2,
              },
              {
                id: 155,
                pid: 132,
                title: "信号分析演练",
                sort: 7,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 133,
            pid: 1,
            title: "导航",
            sort: 4,
            display: 1,
            level: 1,
            child: [
              {
                id: 156,
                pid: 133,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 157,
                pid: 133,
                title: "卫星导航GNSS及北斗模拟测试",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 158,
                pid: 133,
                title: "卫星导航产品综合检测",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 159,
                pid: 133,
                title: "卫星导航抗干扰测试",
                sort: 4,
                display: 1,
                level: 2,
              },
              {
                id: 160,
                pid: 133,
                title: "卫星导航信号采集和回放",
                sort: 5,
                display: 1,
                level: 2,
              },
              {
                id: 161,
                pid: 133,
                title: "卫星导航天线测试",
                sort: 6,
                display: 1,
                level: 2,
              },
              {
                id: 162,
                pid: 133,
                title: "电磁兼容性测试",
                sort: 7,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 134,
            pid: 1,
            title: "半导体",
            sort: 5,
            display: 1,
            level: 1,
            child: [
              {
                id: 163,
                pid: 134,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 164,
                pid: 134,
                title: "半导体晶圆制程",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 165,
                pid: 134,
                title: "半导体封装测试",
                sort: 3,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 135,
            pid: 1,
            title: "射频微波组件",
            sort: 6,
            display: 1,
            level: 1,
            child: [
              {
                id: 166,
                pid: 135,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 167,
                pid: 135,
                title: "无源器件",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 168,
                pid: 135,
                title: "天线",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 169,
                pid: 135,
                title: "放大器",
                sort: 4,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 136,
            pid: 1,
            title: "智能交通",
            sort: 7,
            display: 1,
            level: 1,
            child: [
              {
                id: 170,
                pid: 136,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 171,
                pid: 136,
                title: "泄漏电缆在线监测",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 172,
                pid: 136,
                title: "轨交通信安全保障",
                sort: 3,
                display: 1,
                level: 2,
              },
            ],
          },
          {
            id: 137,
            pid: 1,
            title: "航空航天",
            sort: 99,
            display: 1,
            level: 1,
            child: [
              {
                id: 173,
                pid: 137,
                title: "概述",
                sort: 1,
                display: 1,
                level: 2,
              },
              {
                id: 174,
                pid: 137,
                title: "飞机天馈线系统检测",
                sort: 2,
                display: 1,
                level: 2,
              },
              {
                id: 175,
                pid: 137,
                title: "飞机通信设备发射功率检测",
                sort: 3,
                display: 1,
                level: 2,
              },
              {
                id: 176,
                pid: 137,
                title: "飞行器通信信道仿真测试",
                sort: 4,
                display: 1,
                level: 2,
              },
              {
                id: 177,
                pid: 137,
                title: "GNSS导航系统测试",
                sort: 5,
                display: 1,
                level: 2,
              },
              {
                id: 178,
                pid: 137,
                title: "通信设备综合测试",
                sort: 6,
                display: 1,
                level: 2,
              },
              {
                id: 179,
                pid: 137,
                title: "天线和射频组件测试",
                sort: 7,
                display: 1,
                level: 2,
              },
              {
                id: 180,
                pid: 137,
                title: "无线电干扰监测",
                sort: 8,
                display: 1,
                level: 2,
              },
              {
                id: 181,
                pid: 137,
                title: "复杂电磁环境模拟",
                sort: 9,
                display: 1,
                level: 2,
              },
            ],
          },
        ],
      },
      {
        id: 182,
        pid: 0,
        title: "产品",
        sort: 2,
        display: 1,
        level: 0,
        child: [
          {
            id: 183,
            pid: 182,
            title: "信号发生",
            sort: 1,
            display: 1,
            level: 1,
          },
          {
            id: 184,
            pid: 182,
            title: "信号分析",
            sort: 2,
            display: 1,
            level: 1,
          },
          {
            id: 185,
            pid: 182,
            title: "矢量网络分析",
            sort: 3,
            display: 1,
            level: 1,
          },
          {
            id: 186,
            pid: 182,
            title: "无线网络测试",
            sort: 4,
            display: 1,
            level: 1,
          },
          {
            id: 187,
            pid: 182,
            title: "无线电监测",
            sort: 5,
            display: 1,
            level: 1,
          },
          {
            id: 188,
            pid: 182,
            title: " 卫星导航",
            sort: 6,
            display: 1,
            level: 1,
          },
          {
            id: 189,
            pid: 182,
            title: "信道仿真",
            sort: 7,
            display: 1,
            level: 1,
          },
          {
            id: 190,
            pid: 182,
            title: "航空航天",
            sort: 8,
            display: 1,
            level: 1,
          },
          {
            id: 191,
            pid: 182,
            title: "其他测试",
            sort: 9,
            display: 1,
            level: 1,
          },
        ],
      },
      {
        id: 192,
        pid: 0,
        title: "服务与支持",
        sort: 3,
        display: 1,
        level: 0,
        child: [
          {
            id: 193,
            pid: 192,
            title: "维修校准",
            sort: 1,
            display: 1,
            level: 1,
          },
          {
            id: 194,
            pid: 192,
            title: "资料下载",
            sort: 2,
            display: 1,
            level: 1,
          },
        ],
      },
      {
        id: 195,
        pid: 0,
        title: "关于我们",
        sort: 4,
        display: 1,
        level: 0,
        child: [
          {
            id: 196,
            pid: 195,
            title: "公司简介",
            sort: 1,
            display: 1,
            level: 1,
          },
          {
            id: 197,
            pid: 195,
            title: "投资者关系",
            sort: 2,
            display: 1,
            level: 1,
          },
          {
            id: 198,
            pid: 195,
            title: "公司历史",
            sort: 3,
            display: 1,
            level: 1,
          },
          {
            id: 199,
            pid: 195,
            title: "可持续发展",
            sort: 4,
            display: 1,
            level: 1,
          },
          {
            id: 200,
            pid: 195,
            title: "资质证书",
            sort: 5,
            display: 1,
            level: 1,
          },
          {
            id: 201,
            pid: 195,
            title: "合作伙伴",
            sort: 6,
            display: 1,
            level: 1,
          },
          {
            id: 202,
            pid: 195,
            title: "联系我们",
            sort: 7,
            display: 1,
            level: 1,
          },
          {
            id: 203,
            pid: 195,
            title: "新闻资讯",
            sort: 8,
            display: 1,
            level: 1,
          },
        ],
      },
      {
        id: 204,
        pid: 0,
        title: "招贤纳士",
        sort: 5,
        display: 1,
        level: 0,
        child: [
          {
            id: 205,
            pid: 204,
            title: "校园招聘",
            sort: 1,
            display: 1,
            level: 1,
          },
          {
            id: 206,
            pid: 204,
            title: "社会招聘",
            sort: 2,
            display: 1,
            level: 1,
          },
        ],
      },
    ],
  });
};
